version: "3.8"

services:
  app:
    container_name: "jp_cushon-api"
    build: .
    env_file:
      - .env
    ports:
      - "8080:8080"
    volumes:
      - ./:/app
    depends_on:
      db:
        condition: service_healthy
    entrypoint: CompileDaemon --build="go build cmd/main.go" --command=./main
  db:
    container_name: "jp_cushon-db"
    image: postgres:14
    environment:
      POSTGRES_DB: entdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    user: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U" , "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db_data:
