// Code generated by ent, DO NOT EDIT.

package ent

import (
	"cushon/ent/customer"
	"cushon/ent/deposit"
	"cushon/ent/fund"
	"cushon/ent/schema"
	"time"

	"github.com/google/uuid"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	customerFields := schema.Customer{}.Fields()
	_ = customerFields
	// customerDescName is the schema descriptor for Name field.
	customerDescName := customerFields[1].Descriptor()
	// customer.NameValidator is a validator for the "Name" field. It is called by the builders before save.
	customer.NameValidator = customerDescName.Validators[0].(func(string) error)
	// customerDescID is the schema descriptor for id field.
	customerDescID := customerFields[0].Descriptor()
	// customer.DefaultID holds the default value on creation for the id field.
	customer.DefaultID = customerDescID.Default.(func() uuid.UUID)
	depositFields := schema.Deposit{}.Fields()
	_ = depositFields
	// depositDescCreatedAt is the schema descriptor for created_at field.
	depositDescCreatedAt := depositFields[2].Descriptor()
	// deposit.DefaultCreatedAt holds the default value on creation for the created_at field.
	deposit.DefaultCreatedAt = depositDescCreatedAt.Default.(func() time.Time)
	// depositDescID is the schema descriptor for id field.
	depositDescID := depositFields[0].Descriptor()
	// deposit.DefaultID holds the default value on creation for the id field.
	deposit.DefaultID = depositDescID.Default.(func() uuid.UUID)
	fundFields := schema.Fund{}.Fields()
	_ = fundFields
	// fundDescName is the schema descriptor for Name field.
	fundDescName := fundFields[1].Descriptor()
	// fund.NameValidator is a validator for the "Name" field. It is called by the builders before save.
	fund.NameValidator = fundDescName.Validators[0].(func(string) error)
	// fundDescID is the schema descriptor for id field.
	fundDescID := fundFields[0].Descriptor()
	// fund.DefaultID holds the default value on creation for the id field.
	fund.DefaultID = fundDescID.Default.(func() uuid.UUID)
}
