// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Customer is the predicate function for customer builders.
type Customer func(*sql.Selector)

// Deposit is the predicate function for deposit builders.
type Deposit func(*sql.Selector)

// Fund is the predicate function for fund builders.
type Fund func(*sql.Selector)
